sudo: required
services:
  - docker

language: bash

before_script:
  - docker pull snapcraft/xenial-amd64

script:
  - docker run -v $PWD:$PWD -w $PWD snapcraft/xenial-amd64 snapcraft
  - ls

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "inexor-flex_0.9.0-preview_amd64.snap"
  skip_cleanup: true
  on:
    tags: true
